name: Bug report
description: Report a bug
labels: ["bug"]
assignees: 
  - karjon7

body:
  
  - type: markdown
    attributes:
      value: |
        # Disclaimer
        Thank you for taking the time to fill out the report!
        Please insure the guildines of this template are followed properly. This helps use greatly with identifying issues and resolving much faster.
        -Have
  
  - type: textarea
    attributes:
      label: Tested versions
      description: |
        To properly fix a bug, we need to identify if the bug was recently introduced in the engine, or if it was always present.
        - Please specify the Godot version you found the issue in, including the **Git commit hash** if using a development or non-official build. The exact Godot version (including the commit hash) can be copied by clicking the version shown in the editor (bottom bar) or in the project manager (top bar).
        - If you can, **please test earlier Godot versions** (previous stable branch, and development snapshots of the current feature release) and, if applicable, newer versions (development snapshots for the next feature release). Mention whether the bug is reproducible or not in the versions you tested. You can find all Godot releases in our [download archive](https://godotengine.org/download/archive/).
        - The aim is for us to identify whether a bug is a **regression**, i.e. an issue that didn't exist in a previous version, but was introduced later on, breaking existing functionality. For example, if a bug is reproducible in 4.2.stable but not in 4.1.stable, we would like you to test intermediate 4.2 dev and beta snapshots to find which snapshot is the first one where the issue can be reproduced.
      placeholder: |

        - Reproducible in: 4.3.dev [d76c1d0e5], 4.2.stable, 4.2.dev5 and later 4.2 snapshots.
        - Not reproducible in: 4.1.3.stable, 4.2.dev4 and earlier 4.2 snapshots.
    validations:
      required: true